version: '2'
services:
  db:
    container_name: chain_db
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - /mnt/volumes/chain_db/postgres:/var/lib/postgresql/data
    env_file:
      - config/env.env
networks:
  default:
    external:
      name: chain
